apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: k8s-hands-on
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: backend
spec:
  type: NodePort      
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8 080
      targetPort: 80
      nodePort: 30036
