apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:   
    kubernetes.io/change-cause: "change port to 101"     
  name: deployment-test
  labels:
    app: front
spec:
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine:fake
        ports:
          - containerPort: 101  
